# Use an official Node runtime as a parent image
FROM node:22.3.0

# Set the working directory
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in package.json
RUN npm install

# Ensure the .env file is included
COPY .env .env

# Run the scraper command for 'latest' collection in 'prod' environment
CMD /bin/sh -c "./wrapper-script-docker.sh selected prod"

